version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/
        - ./rabbitmq/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD}
    healthcheck:
        test: rabbitmq-diagnostics check_port_connectivity
        interval: 3s
        timeout: 3s
        retries: 5
        start_period: 5s
    
  server:
    build: ./server
    environment:
      - PORT=${SERVER_PORT}
      - RABBIT_HOSTNAME=${RABBIT_HOSTNAME}
      - RABBIT_USERNAME=${RABBIT_USERNAME}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
    volumes:
      - ./server/src:/app/src
      - ./server/uploads:/app/uploads
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

  worker:
    build: ./worker
    environment:
      - SERVER_URL=http://server:${SERVER_PORT}
      - RABBIT_HOSTNAME=${RABBIT_HOSTNAME}
      - RABBIT_USERNAME=${RABBIT_USERNAME}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
    volumes:
      - ./worker/src:/app/src
    depends_on:
      rabbitmq:
        condition: service_healthy
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip

  mongodb:
    image: mongo:6-jammy
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongodb:/data/db
  